<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 */

$escapeHtml = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-import-files.css', 'BulkImportFiles'));
$script = 'var basePath = ' . json_encode($this->basePath(), 320);
$this->headScript()
    ->appendScript($script)
    ->appendFile($this->assetUrl('js/bulk-import-files.js', 'BulkImportFiles'));
?>
<div class="messages">
    <div class="response"></div>
</div>


<legend>Selected files</legend>

<table class="tablesaw tablesaw-stack" data-tablesaw-mode="stack" id="table-selected-files">
    <thead>
    <tr>

    </tr>
    </thead>
    <tbody>

    <?php foreach ($this->files_data_for_view as $files_data) { ?>

        <?php
        $set_active = '';
        if (isset($files_data['file']['item_id'])) {
            $set_active = 'set_active';
        }
        ?>
        <tr class="separator selected-files-row <?php echo $set_active; ?>">
            <td colspan="1">
                <span>
                    <span>File name:</span>
                    <?php echo $files_data['file']['name']; ?>
                </span>
                <span>
                    <span>File type:</span>
                    <?php
                    $item_id = '';
                    if (isset($files_data['file']['item_id'])) {
                        $item_id = $this->basePath() . '/admin/item/' . $files_data['file']['item_id'] . '/edit';
                        ?>
                        <a target="_blank" class="underline_link" title="Click for edit"
                           href="<?php echo $item_id; ?>"> <?php echo $files_data['file']['type']; ?></a>
                        <input type="hidden" value="<?php echo $files_data['file']['item_id']; ?>"
                               class="omeka_item_id">
                    <?php } else { ?>
                        <?php echo $files_data['file']['type']; ?>
                        <span class="errors">(Type is not defined)</span>
                        <a href="<?= $this->basePath() ?>/admin/item/add" target="_blank" class="add_item_button">Add</a>
                    <?php } ?>



                </span>

                <?php if ($files_data['errors'] == '') : ?>
                    <div class="action-button">
                        <a style="display: none" data-sidebar-content-url="" class="o-icon-delete sidebar-content"
                           title="Delete" href="#"
                           aria-label="Delete"></a>
                        <a data-sidebar-content-url="" class="o-icon-more sidebar-content" title="Show all data"
                           href="#"
                           aria-label="Show all data"></a>
                    </div>

                    <div class="full_info">

                        <table>
                            <tr>
                                <td>Available fields
                                    <div class="js-save-button">
                                        <button type="submit" name="add-item-submit">Save</button>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <table class="tablesaw tablesaw-stack" data-tablesaw-mode="stack" id="subtablesaw">
                                        <thead>
                                        <tr>
                                            <th>Omeka property</th>
                                            <th>Field</th>
                                            <th>Value</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php if ((isset($files_data['exif_data'])) && ($files_data['exif_data'] != '')) { ?>
                                            <?php //var_dump($files_data['exif_data']);?>
                                            <?php foreach ($files_data['exif_data'] as $val) { ?>

                                                <?php
                                                $additional_class = '';
                                                $find_field = '';
                                                ?>

                                                <?php if ((isset($files_data['recognized_data'])) && ($files_data['recognized_data'] != '')) : ?>
                                                    <?php foreach ($files_data['recognized_data'] as $key => $recognized_data_val) { ?>
                                                        <?php if ($recognized_data_val['field'] == substr($val['key'], 1)) {

                                                            $additional_class = 'with_property';

                                                            $find_field .= '<div class="omeka_property">';
                                                            $find_field .= '<span class="omeka_property_name">' . $key . '</span>';
                                                            $find_field .= '<div class="js-action-property-button">';
//                                                        $find_field .= '<span class="js-add-action">+</span>';
                                                            $find_field .= '<span class="js-remove-action">-</span>';
                                                            $find_field .= '</div></div>';

                                                        } ?>

                                                    <?php } ?>
                                                <?php endif; ?>

                                                <?php

                                                if ($additional_class == '') {
                                                    $find_field .= '<div class="omeka_list_property">';
                                                    $find_field .= '</div>';
                                                    $find_field .= '<div class="omeka_property">';
                                                    $find_field .= '<div class="js-action-property-button">';
                                                    $find_field .= '<span class="js-add-action">+</span>';
//                                                $find_field .= '<span class="js-remove-action">-</span>';
                                                    $find_field .= '</div></div>';
                                                } else {
                                                    $find_field .= '<div class="omeka_list_property">';
                                                    $find_field .= '</div>';
                                                    $find_field .= '<div class="omeka_property">';
                                                    $find_field .= '<div class="js-action-property-button">';
                                                    $find_field .= '<span class="js-add-action">+</span>';
                                                    $find_field .= '</div></div>';
                                                }

                                                ?>

                                                <tr attr-property-count="0" class="<?php echo $additional_class; ?>">
                                                    <td><?php echo $find_field; ?></td>
                                                    <td class="js-file_field_property"><?php echo substr($val['key'], 1); ?></td>
                                                    <td>
                                                        <?php echo $val['value']; ?>
                                                    </td>
                                                </tr>

                                            <?php } ?>
                                        <?php } ?>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </table>

                    </div>
                <?php endif; ?>

            </td>

        </tr>
        <?php if ($files_data['errors'] == '') : ?>
            <?php if ((isset($files_data['recognized_data'])) && ($files_data['recognized_data'] != '')) : ?>
                <tr>
                    <td>
                        Recognized fields
                    </td>
                </tr>

                <tr>
                    <td>
                        <table class="tablesaw tablesaw-stack" data-tablesaw-mode="stack" id="subtablesaw">
                            <thead>
                            <tr>
                                <th>Property</th>
                                <th>Field</th>
                                <th>Value</th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php foreach ($files_data['recognized_data'] as $key => $val) { ?>


                                <tr>
                                    <td><?php echo $key; ?></td>
                                    <td><?php echo $val['field']; ?></td>
                                    <td><?php echo $val['value']; ?></td>
                                </tr>

                            <?php } ?>


                            </tbody>
                        </table>
                    </td>


                </tr>
            <?php else : ?>
                <tr>
                    <td class="errors">
                        No recognized fields
                    </td>
                </tr>
            <?php endif; ?>
        <?php else: ?>
            <tr>
                <td class="errors">
                    <div>
                        <?php echo $files_data['errors']; ?>
                    </div>
                </td>
            </tr>

        <?php endif; ?>

    <?php } ?>

    </tbody>
</table>

<div class="listterms type_hidden">
    <div class="listterms_with_action">
        <select class="listterms_select">
            <?php foreach ($this->listTerms as $val) { ?>
                <option value="<?php echo $val; ?>"><?php echo $val; ?></option>
            <?php } ?>

        </select>
        <div class="js-action-property-button">
            <span class="js-single-remove-action">-</span>
        </div>
    </div>

</div>
