<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var array $files_data_for_view
 * @var array $listTerms
 * @var array $filesMaps
 * @var string $error
 */

$translate = $this->plugin('translate');

$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-import-files.css', 'BulkImportFiles'));
$script = 'var basePath = ' . json_encode($this->basePath(), 320);
$this->headScript()
    ->appendScript($script)
    ->appendFile($this->assetUrl('js/bulk-import-files.js', 'BulkImportFiles'), 'text/javascript', ['defer' => 'defer']);
?>

<?php if ($error): ?>

    <div class="error"><?= $error ?></div>

<?php else: ?>

<div class="messages">
    <div class="response"></div>
</div>

<legend><?= $translate('Selected files') ?></legend>

<table class="tablesaw tablesaw-stack" data-tablesaw-mode="stack" id="table-selected-files">
    <thead>
        <tr>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->files_data_for_view as $files_data): ?>
        <?php
        $set_active = isset($files_data['file']['item_id']) ? ' set_active' : '';
        $itemId = isset($files_data['file']['item_id']) ? $files_data['file']['item_id'] : '';
        ?>
        <tr class="separator selected-files-row<?= $set_active ?>" data-file-type="<?= $files_data['file']['type'] ?>" data-file-item-id="<?= $itemId ?>">
            <td colspan="1">
                <span>
                    <span class="label"><?= $translate('File name') ?></span>
                    <span><?= $files_data['file']['name'] ?></span>
                </span>
                <span>
                    <span class="label"><?= $translate('Media type') ?></span>
                    <span><?= $files_data['file']['type'] ?></span>
                    <?php if ($itemId): ?>
                        <a class="small red button file-type delete-file-type" href="#"><?= $translate('Delete') ?></a>
                    <?php else: ?>
                        <a class="small green button file-type add-file-type" href="#"><?= $translate('Add') ?></a>
                    <?php endif; ?>
                </span>
                <span>
                    <?php echo count($files_data['source_data']) ? sprintf($translate('%d available fields'), count($files_data['source_data'])) : $translate('No available fields'); ?>
                </span>

                <?php if (empty($files_data['errors']) || $files_data['errors'] == ""): ?>
                    <div class="action-button">
                        <a style="display: none" data-sidebar-content-url="" class="o-icon-delete sidebar-content"
                           href="#"
                           title="<?= $translate('Delete') ?>"
                           aria-label="<?= $translate('Delete') ?>"></a>
                        <a data-sidebar-content-url="" class="o-icon-more sidebar-content"
                           href="#"
                           title="<?= $translate('Show all data') ?>"
                           aria-label="<?= $translate('Show all data') ?>" style="font-size: 30px; line-height: 15px;">&nbsp;</a>
                    </div>

                    <div class="full_info">
                        <table>
                            <tr>
                                <td>
                                    <?php if (count($files_data['source_data'])): ?>
                                    <?= sprintf($translate('%d available fields'), count($files_data['source_data'])) ?>
                                    <div class="js-save-button">
                                        <button type="submit" name="add-item-submit"><?= $translate('Save') ?></button>
                                    </div>
                                    <?php else: ?>
                                    <?= $translate('No available fields') ?>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <table class="tablesaw tablesaw-stack" data-tablesaw-mode="stack" id="subtablesaw">
                                        <thead>
                                            <tr>
                                                <th><?= $translate('Property') ?></th>
                                                <th><?= $translate('Field') ?></th>
                                                <th><?= $translate($translate('Value')) ?></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php if (!empty($files_data['source_data'])):
                                            //var_dump($files_data['source_data']);
                                            foreach ($files_data['source_data'] as $val):
                                                $additional_class = '';
                                                $find_field = '';

                                                if (!empty($files_data['recognized_data'])):
                                                    foreach ($files_data['recognized_data'] as $recognized_data_val):
                                                        if ($recognized_data_val['field'] == $val['key']):
                                                            $additional_class = 'with_property';
                                                            $find_field .= '<div class="omeka_property">';
                                                            $find_field .= '<span class="omeka_property_name">' . $recognized_data_val['target'] . '</span>';
                                                            $find_field .= '<div class="js-action-property-button">';
                                                            // $find_field .= '<span class="js-add-action">+</span>';
                                                            $find_field .= '<span class="js-remove-action">-</span>';
                                                            $find_field .= '</div></div>';
                                                        endif;
                                                    endforeach;
                                                endif;

                                                if ($additional_class == ''):
                                                    $find_field .= '<div class="omeka_list_property">';
                                                    $find_field .= '</div>';
                                                    $find_field .= '<div class="omeka_property">';
                                                    $find_field .= '<div class="js-action-property-button">';
                                                    $find_field .= '<span class="js-add-action">+</span>';
                                                    // $find_field .= '<span class="js-remove-action">-</span>';
                                                    $find_field .= '</div></div>';
                                                else:
                                                    $find_field .= '<div class="omeka_list_property">';
                                                    $find_field .= '</div>';
                                                    $find_field .= '<div class="omeka_property">';
                                                    $find_field .= '<div class="js-action-property-button">';
                                                    $find_field .= '<span class="js-add-action">+</span>';
                                                    $find_field .= '</div></div>';
                                                endif;
                                            ?>

                                                <tr data-property-count="0" class="<?= $additional_class; ?>">
                                                    <td><?= $find_field; ?></td>
                                                    <td class="js-file_field_property"><?= $val['key'] ?></td>
                                                    <td><?= $val['value'] ?></td>
                                                </tr>

                                            <?php endforeach; ?>
                                        <?php endif; ?>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </table>

                    </div>
                <?php else: ?>
                <?php // echo '--' . $files_data['errors'] . '--';  ?>
                <?php endif; ?>
            </td>

        </tr>
        <?php if (empty($files_data['errors']) || $files_data['errors'] == ''): ?>
            <?php if (!empty($files_data['recognized_data'])): ?>
                <tr>
                    <td><?= $translate('Recognized fields') ?></td>
                </tr>
                <tr>
                    <td>
                        <table class="tablesaw tablesaw-stack" data-tablesaw-mode="stack" id="subtablesaw">
                            <thead>
                                <tr>
                                    <th><?= $translate('Property') ?></th>
                                    <th><?= $translate('Field') ?></th>
                                    <th><?= $translate('Value') ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($files_data['recognized_data'] as $val): ?>
                                    <tr>
                                        <td><?= $val['target'] ?></td>
                                        <td><?= $val['field'] ?></td>
                                        <td><?= $val['value'] ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </td>
                </tr>
            <?php else: ?>
                <tr>
                    <td class="errors"><?= $translate('No recognized fields') ?></td>
                </tr>
            <?php endif; ?>

        <?php else: ?>

            <tr>
                <td class="errors">
                    <div>
                        <?=  $files_data['errors'] ?>
                    </div>
                </td>
            </tr>

        <?php endif; ?>

    <?php endforeach; ?>

    </tbody>
</table>

<?php // TODO Use the default property select. ?>
<div class="listterms type_hidden">
    <div class="listterms_with_action">
        <select class="listterms_select">
            <?php foreach ($listTerms as $vocabulary => $vals): ?>
            <optgroup label="<?= $vocabulary ?>">
                <?php foreach ($vals as $key => $val): ?>
                <option value="<?= $key ?>"><?= $val ?></option>
                <?php endforeach; ?>
            </optgroup>
            <?php endforeach; ?>
        </select>
        <div class="js-action-property-button">
            <span class="js-single-remove-action">-</span>
        </div>
    </div>
</div>

<?php endif; ?>
