<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \BulkImportFiles\Form\ImportForm $form
 */

$translate = $this->plugin('translate');
$escapeHtml = $this->plugin('escapeHtml');

$this->headLink()
    ->appendStylesheet($this->assetUrl('css/bulk-import-files.css', 'BulkImportFiles'));
$script = 'var basePath = ' . json_encode($this->basePath(), 320);
$this->headScript()
    ->appendScript($script)
    ->appendFile($this->assetUrl('js/bulk-import-files.js', 'BulkImportFiles'));

$this->htmlElement('body')->appendAttribute('class', 'bulk-import-files map-edit');

$form->prepare();
?>

<?php echo $this->pageTitle($translate('Create/configure mappings'), 1, $translate('Bulk import files')); ?>

<?php echo $this->form()->openTag($form); ?>
<fieldset id='page-actions'>
    <button type="submit" style="display: none;"><?php echo $translate('Next'); ?></button>
</fieldset>
<?php echo $this->formCollection($form, false); ?>

<div class="selected-files">
</div>

<div class="selected-files-source">
</div>
<?php echo $this->form()->closeTag($form); ?>

<div class="response files-map-block">
    <div class="property">
        <p>
            <?= sprintf($translate('This helper works only with the formats managed by %sGetId3%s.'), '<a href="https://getid3.org" target="_blank">', '</a>') ?>
            <?= $translate('For xml metadata like xmp, that may be more complete and precise, you need to write the xpaths yourself.') ?>
        </p>
        <p>
            <?= sprintf($translate('All fields should have the same format: either the object notation (%siptc.IPTCApplication.Headline%s), either the xpaths (%s/x:xmpmeta/rdf:RDF/rdf:Description/@xmp:Label%s). They should not be mixed.'), '<code>', '</code>', '<code>', '</code>') ?>
        </p>
        <p>
            <?= $translate('You may need to create an item template first, with the media type as title.') ?>
        </p>
        <p>
            <?= $translate('You can select folder with you files with any type (images, etc.) and configure it.') ?>
        </p>
        <h4><?= $translate('Select folder') ?></h4>
        <div><?= $translate('You can select folder with your files with any type (images, etc.) and configure it.') ?></div>
        <div class="inputs">
            <input type="file" name="files[]" id="multiFiles" class="fileinput button" multiple="multiple" webkitdirectory="webkitdirectory" mozdirectory="mozdirectory" msdirectory="msdirectory" odirectory="odirectory" directory="directory">
        </div>
        <?php // This is a hidden button for js. ?>
        <button type="submit" name="upload" id="upload"><?= $translate('Upload') ?></button>
    </div>
</div>

<div class="modal-loader">
    <div class="modal-loader-info"><?= $translate('Please wait, analysis in progress…') ?></div>
</div>
