<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \BulkImportFiles\Form\ImportForm $form
 */

$form->prepare();

$translate = $this->plugin('translate');
$escapeHtml = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulk-import-files.css', 'BulkImportFiles'));
$script = 'var basePath = ' . json_encode($this->basePath(), 320);
$this->headScript()
    ->appendScript($script)
    ->appendFile($this->assetUrl('js/bulk-import-files.js', 'BulkImportFiles'));

?>

<?php echo $this->pageTitle($translate('Create/configure mappings'), 1, $translate('Bulk import files')); ?>

<?php echo $this->form()->openTag($form); ?>
<fieldset id='page-actions'>
    <button type="submit" style="display: none"><?php echo $translate('Next'); ?></button>
</fieldset>
<?php echo $this->formCollection($form, false); ?>

<div class="selected-files">
</div>

<div class="selected-files-source">
</div>

<?php echo $this->form()->closeTag($form); ?>

<div class="files-map-block">
    <div class="property">
        <h4><?= $translate('Select folder'); ?></h4>
        <div><?= $translate('You can select folder with you files, with any type and configure it.'); ?></div>
        <input type="file" id="multiFiles" name="files[]" multiple="multiple" webkitdirectory mozdirectory msdirectory odirectory directory />
        <button id="upload"><?= $translate('Upload') ?></button>
    </div>
</div>
