<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 */

$form->prepare();

$escapeHtml = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/bulkimportfile.css', 'BulkImportFile'));
$this->headScript()->appendFile($this->assetUrl('js/bulkimportfile.js', 'BulkImportFile'));

?>

<?php echo $this->pageTitle($this->translate('Create/configure Import Map'), 1, $this->translate('Bulk import files')); ?>

<?php echo $this->form()->openTag($form); ?>
<fieldset id='page-actions'>
    <button type="submit" style="display: none"><?php echo $this->translate('Next'); ?></button>
</fieldset>
<?php echo $this->formCollection($form, false); ?>


<div class="selected-files">

</div>

<div class="selected-files-source">

</div>

<?php echo $this->form()->closeTag($form); ?>

<div class="files-map-block">

    <div class="property"><h4><?php echo $this->translate('Select folder:'); ?>
            <?php echo $this->translate('(you can select folder with you files, with any type and configure it.)'); ?></h4>

        <input type="file" id="multiFiles" name="files[]" multiple="multiple" webkitdirectory mozdirectory msdirectory
               odirectory directory/>
        <button id="upload">Upload</button>


    </div>
</div>